version: 0.2

env:
  parameter-store:
    ECR_PASSWORD_STDIN: /ecr/password-stdin

phases:
  install:
    commands:
      - echo Entered the install phase...
      - amazon-linux-extras install docker -y
      - yum install git -y
      - git clone https://github.com/ikayarou/notice_shoheiOhtani_homeruns.git
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - systemctl restart docker
      - cd notice_shoheiOhtani_homeruns
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $ECR_PASSWORD_STDIN
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - docker build -t notice-ohtani-homeruns .
      - docker tag notice-ohtani-homeruns:latest $ECR_PASSWORD_STDIN/notice-ohtani-homeruns:latest
      - docker push $ECR_PASSWORD_STDIN/notice-ohtani-homeruns:latest